//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLEIMPUESTOS
    {
        public int dim_id { get; set; }
        public Nullable<int> dep_codigo { get; set; }
        public int imp_id { get; set; }
        public decimal dim_valor { get; set; }
        public string dim_status { get; set; }
    
        public virtual TBL_DETALLEPEDIDO TBL_DETALLEPEDIDO { get; set; }
        public virtual TBL_IMPUESTOS TBL_IMPUESTOS { get; set; }
    }
}
